spring:
  application:
    name: edinor-energy-communities-service

server:
  port: 8100

eureka:
  instance:
    appname: edinor-energy-communities-service
    instance-id: ${spring.application.name}:${server.port}
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
springfox:
  documentation:
    swagger:
      v2:
        host:  localhost:8090
 