spring:
  application:
    name: central-doce-eureka-server
server:
  port: 8761
logging:
  level:
    com.netflix.eureka: false
    com.netflix.discovery: false
    
    
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
    