
############################################################
## Etapa : Package #########################################
############################################################

FROM maven:3.6.3-jdk-8-slim AS ETAPA_MAVEN
WORKDIR /build/
COPY /pom.xml /build/
COPY /src /build/src/
RUN mvn -Dmaven.test.skip=true package

############################################################
## Etapa : Ejecutar ########################################
############################################################


FROM openjdk:8-jre-alpine
WORKDIR /app
COPY --from=ETAPA_MAVEN /build/target/ListadoCochesWEB.war /app/
ENTRYPOINT ["java", "-jar", "ListadoCochesWEB.war"]


# NOTA: Este proyecto tiene dependecia con el proyecto ListadoCochesAPI.


# Crear imagen
# ------------
#  docker image build --no-cache -t listado-coches-web .

# Crear container
# ---------------
#  docker run -p 8081:8081 listado-coches-web

# Probar
# ------
# http://localhost:8081/api/coche/search/findByFechaMatriculacionBetween?inicio=2000-01-01&fin=2020-01-01&page=0size=25sortid,asc